import random
lst = [30, 1, 2, 1, 0]
lst.append(40)
print("Append(40) : ", lst)
lst.insert(1, 43)
print("Insert(1, 43): ", lst)
lst.extend([1, 43])
print("extend(1, 43): ", lst)
lst.remove(30)
print("remove(1): ", lst)
lst.pop(1)
print("pop(1): ", lst)
lst.pop()
print("pop(): ", lst)
lst.sort()
print("sort(): ", lst)
lst.reverse()
print("reverse(): ", lst)
random.shuffle(lst)
print("shuffle(lst): ", lst)
